# Use an official PHP runtime as a parent image
FROM php:8.1-apache

# Install the GD, gettext, mbstring, mysqli, pdo_mysql, and YAZ extensions
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    gettext \
    libonig-dev \
    libyaz-dev \
&& docker-php-ext-configure gd --with-freetype --with-jpeg \
&& docker-php-ext-install -j$(nproc) gd \
&& docker-php-ext-install gettext \
&& docker-php-ext-install mbstring \
&& docker-php-ext-install mysqli \
&& docker-php-ext-install pdo_mysql \
&& pecl install yaz \
&& docker-php-ext-enable yaz

# Set the working directory in the container
WORKDIR /var/www/html

# Copy the current directory contents into the container at /var/www/html
COPY ./app /var/www/html

# Define volumes for persistent data
VOLUME /var/www/html/

# Make directories writable and change ownership
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 777 /var/www/html

# Make port 80 available to the world outside this container
EXPOSE 80

# Run app.py when the container launches
CMD ["apache2-foreground"]
